spring:
  datasource:
    url: jdbc:mysql://gdg-catchme-talk.cp3qxlymbutp.ap-northeast-2.rds.amazonaws.com:3306/catchmetalk?autoReconnect=true
    username: admin
    password: ENC(gw5Cb9fX6XrSXy5028lA79FVLP3sqbAh+B2/NMqMFoXYT0AIUVASfocv4TmVQ4+r)
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch.matching-strategy: ANT_PATH_MATCHER
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      show-sql: true
jwt:
  secretKey: ENC(B1FgbxTzmlM8GG7iIn1uih22Oy1GJ6mKQDSvqg2QojgDfteR+0IX/qlMkrF/n+L5)